// Login Page Actions
export const HANDLE_LOGIN_SUCCESS = 'HANDLE_LOGIN_SUCCESS';
export const HANDLE_LOGIN_FAILURE = 'HANDLE_LOGIN_FAILURE';
export const HANDLE_CREATE_ACCOUNT_SUCCESS = 'HANDLE_CREATE_ACCOUNT_SUCCESS';
export const HANDLE_CREATE_ACCOUNT_FAILURE = 'HANDLE_CREATE_ACCOUNT_FAILURE';

// Portfolio Page Actions
export const HANDLE_CREATE_PORTFOLIO_SUCCESS = 'HANDLE_CREATE_PORTFOLIO_SUCCESS';
export const HANDLE_CREATE_PORTFOLIO_FAILURE = 'HANDLE_CREATE_PORTFOLIO_FAILURE';
export const HANDLE_GET_PORTFOLIO_SUCCESS = 'HANDLE_GET_PORTFOLIO_SUCCESS';
export const HANDLE_GET_PORTFOLIO_FAILURE = 'HANDLE_GET_PORTFOLIO_FAILURE';
export const HANDLE_DELETE_PORTFOLIO_SUCCESS = 'HANDLE_DELETE_PORTFOLIO_SUCCESS';
export const HANDLE_DELETE_PORTFOLIO_FAILURE = 'HANDLE_DELETE_PORTFOLIO_FAILURE';
export const HANDLE_GET_ORDERS_SUCCESS = 'HANDLE_GET_ORDERS_SUCCESS';
export const HANDLE_GET_ORDERS_FAILURE = 'HANDLE_GET_ORDERS_FAILURE';
export const HANDLE_PLACE_ORDER_SUCCESS = 'HANDLE_PLACE_ORDER_SUCCESS';
export const HANDLE_PLACE_ORDER_FAILURE = 'HANDLE_PLACE_ORDER_FAILURE';
export const HANDLE_CANCEL_ORDER_SUCCESS = 'HANDLE_CANCEL_ORDER_SUCCESS';
export const HANDLE_CANCEL_ORDER_FAILURE = 'HANDLE_CANCEL_ORDER_FAILURE';

// Stocks Page Actions
export const HANDLE_GET_ALL_STOCKS_SUCCESS = 'HANDLE_GET_ALL_STOCKS_SUCCESS';
export const HANDLE_GET_ALL_STOCKS_FAILURE = 'HANDLE_GET_ALL_STOCKS_FAILURE';
export const HANDLE_TRENDS_REFRESH_SUCCESS = 'HANDLE_TRENDS_REFRESH_SUCCESS';
export const HANDLE_TRENDS_REFRESH_FAILURE = 'HANDLE_TRENDS_REFRESH_FAILURE';
export const HANDLE_GET_DETAILS_SUCCESS = 'HANDLE_GET_DETAILS_SUCCESS';
export const HANDLE_GET_DETAILS_FAILURE = 'HANDLE_GET_DETAILS_FAILURE';

// IPO Page Actions
export const HANDLE_NEW_IPO_SUCCESS = 'HANDLE_NEW_IPO_SUCCESS';
export const HANDLE_NEW_IPO_FAILURE = 'HANDLE_NEW_IPO_FAILURE';

// Settings Page Actions
export const HANDLE_CHANGE_PASSWORD_SUCCESS = 'HANDLE_CHANGE_PASSWORD_SUCCESS';
export const HANDLE_CHANGE_PASSWORD_FAILURE = 'HANDLE_CHANGE_PASSWORD_FAILURE';

// Error Messages
export const ERROR_UNEXPECTED = 'An unexpected error occurred';


