// Login Page Actions
export const HANDLE_LOGIN_SUCCESS = 'HANDLE_LOGIN_SUCCESS';
export const HANDLE_LOGIN_FAILURE = 'HANDLE_LOGIN_FAILURE';
export const HANDLE_CREATE_ACCOUNT_SUCCESS = 'HANDLE_CREATE_ACCOUNT_SUCCESS';
export const HANDLE_CREATE_ACCOUNT_FAILURE = 'HANDLE_CREATE_ACCOUNT_FAILURE';

// Portfolio Page Actions
export const HANDLE_CREATE_PORTFOLIO_SUCCESS = 'HANDLE_CREATE_PORTFOLIO_SUCCESS';
export const HANDLE_DELETE_PORTFOLIO_SUCCESS = 'HANDLE_DELETE_PORTFOLIO_SUCCESS';
export const TEST_BEAR = 'TEST_BEAR';
