export const HANDLE_LOGIN_SUCCESS = 'HANDLE_LOGIN_SUCCESS';
export const HANDLE_LOGIN_FAILURE = 'HANDLE_LOGIN_FAILURE';
export const HANDLE_CREATE_ACCOUNT_SUCCESS = 'HANDLE_CREATE_ACCOUNT_SUCCESS';
export const HANDLE_CREATE_ACCOUNT_FAILURE = 'HANDLE_CREATE_ACCOUNT_FAILURE';
export const TEST_BEAR = 'TEST_BEAR';
